name: templater_atreeon
description: Text Template Transformation or T4 template alternative
version: 1.0.0
repository: https://github.com/atreeon/templater_atreeon/

environment:
  sdk: '>=2.17.3 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
